# -*- coding: utf-8 -*-
"""AEMET_MEJORA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t8KURdidOKRnjElxrgLcz_1B__weli1w
"""

import requests
import json
import pandas as pd






######FUNCION LEER ARCHIVO TXT CON NOMBRE ESTACIONES Y EJECUTAR#####
def read_and_exec():
  f = open("Prova.txt", "r",encoding='utf8') #####TXT donde lee estaciones##### 
  for x in f:
    x=x.rstrip("\n")
    Estacion_horas(x)
  f.close()

########################################################


######FUNCION UTILIZADA####NO TOCAR###DEVUELVE CSV CON NOMBRE FORMATO: "AEMET"+FECHA+UBI+ESTACION

def Estacion_horas(Estation):

  #TOKEN Y GET PARA CONSEGUIR LOS DATOS DE AEMET
  url = "https://opendata.aemet.es/opendata/api/observacion/convencional/datos/estacion/"+Estation
  querystring = {"api_key":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlcGVuZ2luZWVyQGdtYWlsLmNvbSIsImp0aSI6IjEzYzdhMzdjLTQ1ODctNGFiYy05Mjk1LWNmODA3N2Y1YTRmMyIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNjE5MTc3OTExLCJ1c2VySWQiOiIxM2M3YTM3Yy00NTg3LTRhYmMtOTI5NS1jZjgwNzdmNWE0ZjMiLCJyb2xlIjoiIn0.yFcrL_tX4T-XSLsExWY_kD2Af2U3YGYIE5eGbuqJYiQ"}

  headers = {
      'cache-control': "no-cache"
      }
  #####

  ####DOBLE GET PARA CONSEGUIR LOS DATOS FINALS Y PASARLOS A JSON

  response = requests.request("GET", url, headers=headers, params=querystring)
  data=response.json()
  print(response.text)
  response2 = requests.request("GET", data["datos"], headers=headers, params=querystring)
  data2=response2.json()
  ##########

  ###CONVERTIMOS A DATAFRAME
  N_Variables=len(data2[0])-1
  #print(N_Variables)
  i=0
  df = pd.DataFrame()
  while i<N_Variables:
    Valores1=data2[i]
    Dentro=data2[0]
    a=json.dumps(Dentro)
    Diccionario_var=[]
    #print(Valores1)
    Valores=[]
    for key in json.loads(a):
      Diccionario_var.append("columna_"+key)
      Valores.append(Valores1[key])   
    df=df.append(pd.Series(Valores1), ignore_index=True) 
    i=i+1
  Nombre_ubi=str(df.ubi[0])
  Nombre_tiempo=str(df.fint[10])
  Nombre_Total="AEMET"+" "+Nombre_tiempo[0:10]+" "+Nombre_ubi+" "+Estation+".csv"
  df.to_csv(Nombre_Total,index=False)



############EJECUTAMOS FUNCION PRINCIPAL PROGRAMA##############
read_and_exec() ###SI NO FUNCIONA SITUAMOS AL FINAL
############################################################